
language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

branches:
  only:
  - master

install:
  - git clone --depth 1 https://github.com/Jermolene/TiddlyWiki5.git
  - cd TiddlyWiki5
  - npm link
  - cd ..

script:
  - tiddlywiki --verbose --build index

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TIDDLYWIKI_GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: output
  on:
    branch: master
